spring:
  application:
    name: timesheet-app

  # Production Database Configuration (PostgreSQL)
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/timesheetdb}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Disable H2 console in production
  h2:
    console:
      enabled: false

# Server Configuration
server:
  port: ${PORT:8080}
  servlet:
    context-path: /

# Logging Configuration
logging:
  level:
    com.timesheet: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN

# Custom Application Properties
app:
  jwt:
    secret: ${JWT_SECRET:timesheetProductionSecretKey2024VerySecure}
    expiration: 86400000 # 24 hours in milliseconds
